### ISSUE TITLE
Cannot install sstsne

### ISSUE THREAD

**Issue by constance-scherer** [lmcinnes/sstsne#1]
Hello,

I have been trying to install your repository for Semi Supervised t-SNE and I've been running into an error that prevents me from completing the install.

Here is the error message :
`17.36 sstsne/_barnes_hut_tsne.c:25840:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
#9 17.36      tstate->exc_traceback = *tb;
#9 17.36              ^~~~~~~~~~~~~
#9 17.36              curexc_traceback
#9 17.50 In file included from /usr/local/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:21,
#9 17.50                  from /usr/local/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
#9 17.50                  from sstsne/_barnes_hut_tsne.c:267:
`

The same error happens for exc_type and exc_value.

I've tried the install on both Windows 10 and Linux Debian.
My configuration is as follow:
- Python 3.7 and 3.8
- Cython 0.29.23 and 0.29.24
-  libgfortran5 amd64 8.3.0-6
- libopenblas-base amd64 0.3.5+ds-3 
- libopenblas-dev amd64 0.3.5+ds-3

Thanks in advance,
Constance

**Comment by constance-scherer** [comment]
Forcing the regeneration of _barnes_hut_tsne.c on Linux (by removing the file before launching the install) resolved the issue and I was able to complete the install.
From my understanding, this is due to an incompatibility between previous Cython versions (likely used when this repo was made) and newer python version (above 3.7, I think). 
Unfortunately, this wasn't enough to solve the issue on Windows, it lead me to another error having to do with external symbols not being properly recognized (in particular cblas_snrm2). I reckon this error is linked to my OpenBLAS install, but I wasn't able to find many leads to resolve it. I found one [https://stackoverflow.com/questions/63750020/unresolved-external-symbol-error-when-linking-a-cython-extension-against-a-c-l](url) article where the problem seemed similar enough but I wasn't able to apply it to my problem. 
Since I am no longer trying to make it work on Windows, I'll close the issue.

**Comment by lmcinnes** [comment]
Thanks for reporting this -- I'll be honest this code is not really maintained anymore (the ideas that went in to this got moved over to UMAP which is actively maintained). The dependence on Cython means that the code really needs to be re-cythonized and completely recompiled for any install, and that may be challenging on Windows where compilation is trickier.
